---
title: "mosquito-template-scrap"
output: html_document
---

##Introduction
To many, mosquitos are nothing more than a seasonal annoyance. However, 
mosquitos are important for their role in the transmission of human diseases. 
For example, the species Aedes albopictus is notable in North America for its 
ability to spread the West Nile Virus and its association with human inhabited 
urbanized environments (Rochlin et al. 2013). As the environment changes in 
response to global warming, it is likely that the ranges and habits of mosquitos
like Aedes albopictus will also change. Differences in mosquito habits over time
could put an increased number of people at risk for contracting mosquito-borne 
diseases, so it is important to investigate the various facets of mosquitos 
interacting with their environments. 

This tutorial will provide a preliminary look at three different avenues of 
investigation. First, we will examine whether there is a relationship between 
mosquito species richness and latitude in the United States. The latitudinal 
diversity gradient (LDG) has been explored in other species such as shore fishes
and African birds, but little work has been done on LDGs for mosquitos. In this 
tutorial we will transform NEON data to construct preliminary models of mosquito
species richness in relation to latitude. A second aspect of mosquito data under
consideration is the Julian date of first occurrence for certain species of 
mosquitos. In particular in this tutorial we will be examining the species Culex
tarsalis because of their abilities to transmit diseases and their relative 
presence in the NEON data. 

```{r}
# Katie LeVan: 
# temp.df$date[temp.df$date > early & temp.df$date <late]
# and loop through the window
# Charlotte Roiger: 
# what do you mean by early and late? 
# Katie LeVan: 
# early could be a variable that was your first date of the range
# and late could be the other bookend of the window
# for instance

########################### WORK FOR TEMP LAG #####################################################

#Goal for lag code: For each date and site in the ID df I want to create code that will find that corresponding date and site and take only the rows up to two weeks prior to that date for that location and take the average temperature. 

Templag <- function(siteID, date){
  date <- as.Date(date)
  filter1 <- temp.df[grepl(siteID, temp.df$siteID),]
  filter2 <- filter1[filter1$date > date - 14 & filter1$date < date + 1,]
  TwoWeekAvgT <- mean(filter2$value)/10
  return(TwoWeekAvgT)
}

tiny.df$siteid<-as.character(tiny.df$siteid)
tiny.df<- id2016[1:6,]
Templag('ABBY', as.numeric(2012-03-04))

TwoWeekAvgMaxTemp<-mapply(Templag, tiny.df$siteid, tiny.df$date)

tiny.df<-cbind(tiny.df, TwoWeekAvgMaxTemp)

```

