---
title: "Roiger Intern Project Preliminary Code"
author: "Charlotte Roiger"
output:
  html_document: default
  word_document: default
---
###Data Frame Set Up

```{r,message=FALSE}
# install.packages('tidyverse')
library(tidyverse)
library(mosaic)
library(plyr)

trap = read.csv('N:/Science/FSU/Intern Projects/2107_CharlotteRoiger/mos_trapping_in.csv')
sort = read.csv('N:/Science/FSU/Intern Projects/2107_CharlotteRoiger/mos_sorting_in.csv')
id = read.csv('N:/Science/FSU/Intern Projects/2107_CharlotteRoiger/mos_identification_in.csv')
pathogen = read.csv('N:/Science/FSU/Intern Projects/2107_CharlotteRoiger/mos_pathogenresults_in.csv')
taxonomy.df = read.csv("~/mosquito-intern/resources/mosquito_taxonomy.csv")
precip.df = read.csv('~/mosquito-intern/resources/precipitation.csv')
temp.df = read.csv("~/mosquito-intern/resources/temperature_maximum.csv")
domain.df = read.csv("~/mosquito-intern/data/domainid_siteid_match.csv")
source('~/mosquito-intern/code/get_NEON_location.R')
# source('~/GitHub/mosquito-intern/code/get_NEON_location.R') # this is Cody's file path
uniquePlotIDs <- unique(trap$plotID)

## apply get_NEON_location function to vector uniquePlotIDs, returns a list where each element is a single plotID with GPS data

# st <- Sys.time() # profiling start time
latlon <- lapply(uniquePlotIDs, get_NEON_location, output="latlon")
# end <- Sys.time(); end - st # profiling end time; calculate function execution duration

## convert list into data.frame
latlon.df <- do.call(rbind, latlon)
## matching the names of your columns
names(latlon.df) <- c("uniquePlotIDs", "lat", "lon", "northing", "easting", "utmZone", "elevation") 

#Removing datapoint with lat lon listed as 1,1
latlon.df[latlon.df==1]<-NA

trap$plotID<-as.character(trap$plotID)

#Merging trap df with lat lon data
trap <- merge(x = latlon.df, y = trap, by.x = "uniquePlotIDs", by.y = "plotID") #merge example

#Filling in more lat lon data
trap$lat2<-ifelse(is.na(trap$lat)==TRUE, trap$pdaDecimalLatitude,trap$lat)
trap$lon2<-ifelse(is.na(trap$lon)==TRUE, trap$pdaDecimalLongitude,trap$lon)

#Creating a dataframe with only the unique plotIDs and lat2 lon2 data for merging
uniquetrap<-trap[!duplicated(trap[,1]),c("uniquePlotIDs","lat2","lon2")]

# Merge ID with sort
cols = colnames(sort)[!colnames(sort)%in%colnames(id)]
id <- left_join(id, sort[, c('subsampleID', cols)], 
                by = "subsampleID")

#Changing plotID from factor to character to prevent errors
id$plotID<-as.character(id$plotID)

#Merging id df with lat2 lon2 data
id <- merge(x = uniquetrap, y = id, by.y = "plotID", by.x = "uniquePlotIDs")

# Get zero traps from trapping
new_trap<- trap[!trap$sampleID %in% id$sampleID & trap$targetTaxaPresent=="N",]

#Add columns in new_trap that weren't present in the ID table then add new_trap to ID table
new_trap <- new_trap[, colnames(new_trap)[colnames(new_trap)%in%colnames(id)]]

new_trap[, colnames(id)[!colnames(id)%in%colnames(new_trap)]]<-NA

id <- rbind(id,new_trap)

#Extracting year information for id
id$Year<-substr(id$collectDate,1,4)

#Chaning year to be a factor rather than a character
id$Year<-as.factor(id$Year)

#Exctracting date information for id
id$Date<-substr(id$setDate,1,10)

#Broad Site ID variable CHANGE TO REFLECT OTHER CODE I.E UNQUEPLOTIDS
id$siteID<-substr(id$uniquePlotIDs,1,4)

#merging id with temp data
id <- merge(x = temp.df, y = id, by.y = c('siteID','Date'), by.x = c('siteID','date'), all.y = TRUE)

#Converting temperature to proper value
id$value<-id$value/10
names(id)[5]<-"Max.TempC"

#Merge id with precip data
id <- merge(x = precip.df[,c(1,4,9)], y = id, by.y = c('siteID', 'date'), by.x = c('siteID', 'date'), all.y = TRUE)

#converting temperature to proper value and renaming
id$value<-id$value/10
names(id)[3]<-"Precipmm"

#Merge with domain info.
id <- merge(x = domain.df, y = id, by.y = "siteID", by.x = "siteid", all.y = TRUE)
id$domainid <- as.character(id$domainid)

#Working on time difference offset variable

#Checks to see if all obs are on the same day or two different days and nothing else
tally(substr(id$setDate,9,10)==substr(id$collectDate,9,10))
tally(substr(id$setDate,9,10)!=substr(id$collectDate,9,10))

#Variable that contains the time difference between set and collection in hours
id$Timediff<-ifelse(substr(id$setDate,9,10)!=substr(id$collectDate,9,10), 24 - ((as.numeric(substr(id$setDate,15,16))/60)+(as.numeric(substr(id$setDate,12,13)))) + ((as.numeric(substr(id$collectDate,15,16))/60)+(as.numeric(substr(id$collectDate,12,13)))),((as.numeric(substr(id$collectDate[8],15,16))/60)+(as.numeric(substr(id$collectDate[8],12,13)))) - ((as.numeric(substr(id$setDate[8],15,16))/60)+(as.numeric(substr(id$setDate[8],12,13)))))

#Changing Time diff to numeric
id$Timediff <- abs(as.numeric(id$Timediff))

#Creation of sample Multiplier
id$sampleMultiplier <- ifelse(is.na(id$bycatchWeight)==F,id$totalWeight/(id$subsampleWeight-id$bycatchWeight), NA)
id$sampleMultiplier <- ifelse(id$sampleMultiplier==Inf, NA, id$sampleMultiplier)

#Creation of New individual Count with Multiplier
id$newindividualCount <-ifelse(is.na(id$sampleMultiplier)==F, round(id$individualCount*id$sampleMultiplier), NA)

#Year subsets
id2012<-id[id$Year==2012,]
id2013<-id[id$Year==2013,]
id2014<-id[id$Year==2014,]
id2015<-id[id$Year==2015,]
id2016<-id[id$Year==2016,]

```


###Species Richness Vignette

```{r}
#If I merge dataframes then it automatically removes the null plot ID

#Creation of a dataframe that maps plotIds to number of unique scientific names
specrich <- ddply(id, ~ uniquePlotIDs + collectDate + Year + Timediff + Precipmm + Max.TempC, summarize, num_species = length(scientificName))

# 
# #Merging to get lat2 lon2 data
specrich <- merge(x = uniquetrap, y = specrich, by.y = "uniquePlotIDs", by.x = "uniquePlotIDs")

#Changin year to a factor
specrich$Year<-as.factor(specrich$Year)

#Creation of Year subsets
specrich2012 <- specrich[specrich$Year==2012,]
specrich2013 <- specrich[specrich$Year==2013,]
specrich2014 <- specrich[specrich$Year==2014,]
specrich2015 <- specrich[specrich$Year==2015,]
specrich2016 <- specrich[specrich$Year==2016,]

```



###Julian Date of first occurence versus lat

```{r}
#Over representation of females in ID sample
tally(id$sex)

#Table of proportions of female versus male over time
prop.table(table(id$Year,id$sex),1)

#Instances of Ae. albopictus by year
table(id$Year,id$scientificName=="Aedes albopictus")

#Number of times each species identified in id df
tally(id$scientificName)

#Tracking number of sites where Ae. Albopictus has been identified
albo<- id[grepl("Aedes albopictus", id$scientificName),]
albo2014<- id2014[grepl("Aedes albopictus", id2014$scientificName),]
albo2015<- id2015[grepl("Aedes albopictus", id2015$scientificName),]
albo2016<- id2016[grepl("Aedes albopictus", id2016$scientificName),]

#ex of previous code
#albo <- id[id$scientificName=="Aedes albopictus",]


length(unique(albo2014$uniquePlotIDs)) #18
length(unique(albo2015$uniquePlotIDs)) #9
length(unique(albo2016$uniquePlotIDs)) #45

#Preliminary findings suggest large amount of fluctuation in number of sites, could be due to sampling procedure or changes in biotic variables at each site

#Sum of Ae. albopictus for each year
sum(na.omit(albo2014$newindividualCount)) # 69
sum(na.omit(albo2015$newindividualCount)) # 43
sum(na.omit(albo2016$newindividualCount)) # 433

#Proportion of Ae. albopictus relative to total number collected by year
sum(complete.cases(albo2014$newindividualCount))/sum(complete.cases(id2014$newindividualCount))
sum(complete.cases(albo2015$newindividualCount))/sum(complete.cases(id2015$newindividualCount))
sum(complete.cases(albo2016$newindividualCount))/sum(complete.cases(id2016$newindividualCount))

#Slight increase in proportion of Ae. Albopictus caught over time relative to total number of mosquitos caught exception of 2016.

#Create df for domain ID and native code

albotax <- tidyr:: gather(taxonomy.df[grepl("Aedes albopictus", taxonomy.df$scientificName), grepl("NativeStatusCode", colnames(taxonomy.df))], "Domain ID")

albotax<-albotax[c(5:15,17:23),]

albotax.df <-data.frame("domainID"= unique(domain.df$domainid), "DomainNativeStatus"= albotax)

#Merge Cu. tarsalis taxonomy df with albo df
albo <- merge(x = albotax.df, y = albo, by.x = "domainID", by.y = "domainid")

#Subsets containing only the rows where Cu. tarsalis was first sampled in each geographic subdivision
albo.firstdomain <- albo[match(unique(albo$domainID), albo$domainID),]
albo.firstsite <- albo[match(unique(albo$siteid), albo$siteid),]
albo.firstplot <- albo[match(unique(albo$uniquePlotIDs), albo$uniquePlotIDs),]

############## Culex tarsalis #########################

#Instances of Cu. tarsalis by Year
table(id$Year, id$scientificName=="Culex tarsalis")

#Tracking number of sites where Cu. tarsalis has been identified
tars<- id[grepl("Culex tarsalis", id$scientificName),]
tars2013<- id2013[grepl("Culex tarsalis", id2013$scientificName),]
tars2014<- id2014[grepl("Culex tarsalis", id2014$scientificName),]
tars2016<- id2016[grepl("Culex tarsalis", id2016$scientificName),]

#Examples of tars<- id[id$scientificName=="Culex tarsalis",]

#Create df for domain ID and native code

tarstax <- tidyr:: gather(taxonomy.df[grepl("Culex tarsalis", taxonomy.df$scientificName), grepl("NativeStatusCode", colnames(taxonomy.df))], "Domain ID")

tarstax<-tarstax[c(5:15,17:23),]

tarstax.df <-data.frame("domainID"= unique(domain.df$domainid), "DomainNativeStatus"= tarstax)

#Merge Cu. tarsalis taxonomy df with tars df
tars <- merge(x = tarstax.df, y = tars, by.x = "domainID", by.y = "domainid")

#number of sites of appearance
length(unique(tars$uniquePlotIDs)) #160
length(unique(tars2013$uniquePlotIDs)) #35
length(unique(tars2014$uniquePlotIDs)) #40
length(unique(tars2016$uniquePlotIDs)) #115


#Sum of Cu. tarsalis for each year
sum(tars2013$newindividualCount) # 1,690
sum(tars2014$newindividualCount) # 17,432
sum(na.omit(tars2016$newindividualCount)) # 11,827

#Proportion of Cu. tarsalis relative to total number collected by year
sum(complete.cases(tars2013$newindividualCount))/sum(complete.cases(id2013$newindividualCount))
sum(complete.cases(tars2014$newindividualCount))/sum(complete.cases(id2014$newindividualCount))
sum(complete.cases(tars2016$newindividualCount))/sum(complete.cases(id2016$newindividualCount))

#Subsets containing only the rows where Cu. tarsalis was first sampled in each geographic subdivision
tars.firstdomain <- tars[match(unique(tars$domainID), tars$domainID),]
tars.firstsite <- tars[match(unique(tars$siteid), tars$siteid),]
tars.firstplot <- tars[match(unique(tars$uniquePlotIDs), tars$uniquePlotIDs),]

 
```

############################ Working until this point ###########################################

###Graphs and Visualizations

```{r}
######## NEED TO FIX TO MELD WITH CURRENT ID DATAFRAME CURRENT CODE BROKEN ##############
#Preliminary graph of latitude by species richness overall
# ggplot(specrich,aes(lat2, num_species))+
#   geom_point(aes(colour = num_species))+
#   ggtitle("Species Richness by Latitude all years")

#Scatterplot with regression fit for 2012 ng
# ggplot(mod2012$model,aes(lat2, num_species))+
#   geom_point(aes(colour = num_species))+
#   ggtitle("Species Richness by Latitude in 2012")+
#   stat_smooth(method = "lm", col = "red")

#Preliminary graph of latitude by species richness for 2013
# ggplot(specrich2013,aes(lat2, num_species))+
#   geom_point(aes(colour = num_species))+
#   ggtitle("Species Richness by Latitude in 2013")

#Scatterplot with regression fit for 2014 nb
# ggplot(mod2014$model,aes(lat2, num_species))+
#   geom_point(aes(colour = num_species))+
#   ggtitle("Species Richness by Latitude in 2014")+
#   stat_smooth(method = "lm", col = "red")

#Scatterplot with regression fit for 2015 ng 
# ggplot(mod2015$model,aes(lat2, num_species))+
#   geom_point(aes(colour = num_species))+
#   ggtitle("Species Richness by Latitude in 2015")+
#   stat_smooth(method = "lm", col = "red")

#Scatterplot with regression fit for 2016 g
# ggplot(mod2016$model,aes(lat2, num_species))+
#   geom_point(aes(colour = num_species))+
#   ggtitle("Species Richness by Latitude in 2016")+
#   stat_smooth(method = "lm", col = "red")

#Visualization of proportion of female mosquitos over time
# ggplot(id, aes(x = Year, fill = sex)) +
#   geom_bar(position = "fill")+
#   labs(y = "Proportions")+
#   ggtitle("Proportions of Female Mosquitos by Year")

#Max Temp for Year 2012
# ggplot(specrich2012, aes(as.Date(collectDate), Max.TempC)) +
#   geom_point(aes(colour = num_species)) +
#   labs(x = "Date", y = "Maximum Temperature in Celsius") +
#   ggtitle("Maximum Temperature for the Year 2012")

#Max Temp for Year 2013
# ggplot(specrich2013, aes(as.Date(collectDate), Max.TempC)) +
#   geom_point(aes(colour = num_species)) +
#   labs(x = "Date", y = "Maximum Temperature in Celsius") +
#   ggtitle("Maximum Temperature for the Year 2013")


#Max Temp for Year 2014
# ggplot(specrich2014, aes(as.Date(collectDate), Max.TempC)) +
#   geom_point(aes(colour = num_species)) +
#   labs(x = "Date", y = "Maximum Temperature in Celsius") +
#   ggtitle("Maximum Temperature for the Year 2014")


#Max Temp for Year 2015
# ggplot(specrich2015, aes(as.Date(collectDate), Max.TempC)) +
#   geom_point(aes(colour = Precipmm)) +
#   labs(x = "Date", y = "Maximum Temperature in Celsius") +
#   ggtitle("Maximum Temperature for the Year 2015")


#Max Temp for Year 2016
# ggplot(specrich2016, aes(as.Date(collectDate), Max.TempC)) +
#   geom_point(aes(colour = num_species)) +
#   labs(x = "Date", y = "Maximum Temperature in Celsius") +
#   ggtitle("Maximum Temperature for the Year 2016")


#Precip for Year 2012
# ggplot(specrich2012, aes(as.Date(collectDate), Precipmm)) +
#   geom_point(aes(colour = num_species)) +
#   labs(x = "Date", y = "Precipitation in mm") +
#   ggtitle("Precipitation for the Year 2012")

#Precip for Year 2013
# ggplot(specrich2013, aes(as.Date(collectDate), Precipmm)) +
#   geom_point(aes(colour = num_species)) +
#   labs(x = "Date", y = "Precipitation in mm") +
#   ggtitle("Precipitation for the Year 2013")

#Precip for Year 2014
# ggplot(specrich2014, aes(as.Date(collectDate), Precipmm)) +
#   geom_point(aes(colour = num_species)) +
#   labs(x = "Date", y = "Precipitation in mm") +
#   ggtitle("Precipitation for the Year 2014")

#Precip for Year 2015
# ggplot(specrich2015, aes(as.Date(collectDate), Precipmm)) +
#   geom_point(aes(colour = num_species)) +
#   labs(x = "Date", y = "Precipitation in mm") +
#   ggtitle("Precipitation for the Year 2015")

#Precip for Year 2016
# ggplot(specrich2016, aes(as.Date(collectDate), Precipmm)) +
#   geom_point(aes(colour = num_species)) +
#   labs(x = "Date", y = "Precipitation in mm") +
#   ggtitle("Precipitation for the Year 2016")


```

###Preliminary Modeling

```{r}
#Preliminary Linear mods

# mod2012 <-lm(num_species~lat2,data=specrich2012) #Sparse
# summary(mod2012)
# 
# #omitted 2013 model due to lack of viable data to form model
# 
# mod2014 <-lm(num_species~lat2,data=specrich2014)
# summary(mod2014)
# 
# mod2015 <-lm(numspecies~lat2,data=specrich2015) #Sparse
# summary(mod2015)
# 
# mod2016 <-lm(num_species~lat2,data=specrich2016)
# summary(mod2016)
# 
# modallyears <- lm(num_species~lat2, data=specrich)
# summary(modallyears)
# 
# modyearfactor <- lm(num_species~lat2 + Year, data = specrich)
# summary(modyearfactor)
# 
# #Precipitation Models
# precip.mod2012 <- lm(num_species~lat2 + Precipmm, data = specrich2012)
# summary(precip.mod2012)
# 
# precip.mod2014 <- lm(num_species~lat2 + Precipmm, data = specrich2014)
# summary(precip.mod2014)
# 
# precip.mod2015 <- lm(num_species~lat2 + Precipmm, data = specrich2015)
# summary(precip.mod2015)
# 
# precip.mod2016 <- lm(num_species~lat2 + Precipmm, data = specrich2016)
# summary(precip.mod2016)
# 
# precip.modallyears <- lm(num_species~lat2 + Precipmm, data=specrich)
# summary(precip.modallyears)
# 
# precip.modyearfactor <- lm(num_species~lat2 + Precipmm + Year, data = specrich)
# summary(precip.modyearfactor)
# 
# #Max Temp Models
# maxtemp.mod2012 <- lm(num_species~lat2 + Max.TempC, data = specrich2012)
# summary(maxtemp.mod2012)
# 
# maxtemp.mod2014 <- lm(num_species~lat2 + Max.TempC, data = specrich2014)
# summary(maxtemp.mod2014)
# 
# maxtemp.mod2015 <- lm(num_species~lat2 + Max.TempC, data = specrich2015)
# summary(maxtemp.mod2015)
# 
# maxtemp.mod2016 <- lm(num_species~lat2 + Max.TempC, data = specrich2016)
# summary(maxtemp.mod2016)
# 
# maxtemp.modallyears <- lm(num_species~lat2 + Max.TempC, data = specrich)
# summary(maxtemp.modallyears)
# 
# maxtemp.modyearfactor <- lm(num_species~lat2 + Max.TempC + Year, data = specrich)
# summary(maxtemp.modyearfactor)
# 
# #Maxtemp and precip combination models
# 
# combo.mod2012 <- lm(num_species~lat2 + Precipmm + Max.TempC, data = specrich2012)
# summary(combo.mod2012)
# 
# combo.mod2014 <- lm(num_species~lat2 + Precipmm + Max.TempC, data = specrich2014)
# summary(combo.mod2014)
# 
# combo.mod2015 <- lm(num_species~lat2 + Precipmm + Max.TempC, data = specrich2015)
# summary(combo.mod2015)
# 
# combo.mod2016 <- lm(num_species~lat2 + Precipmm + Max.TempC, data = specrich2016)
# 
# combo.modallyears <- lm(num_species~lat2 + Precipmm + Max.TempC, data = specrich)
# summary(combo.modallyears)
# 
# combo.modyearfactor <- lm(num_species~lat2 + Precipmm + Max.TempC + Year, data = specrich)
# summary(combo.modyearfactor)

```

```{r}
#Multi Level Linear Modeling
# library(lme4)

#Level one vars measured at each sample: Time Diff
#level two vars measured at each site: Latitude, Precip, Temperature
#level three vars measured at each domain: NLDC
#Unconditional means model
# Null.mll <- lmer(num_species ~ 1 + (1|uniquePlotIDs), REML= F, data=specrich)
# summary(Null.mll)
# 
# Latonly.mll <- lmer(num_species ~ lat2 + (1|uniquePlotIDs), REML = F, data = specrich)
# summary(Latonly.mll)
# 
# Latonly2.mll <- lmer(num_species ~ lat2 * Timediff + (Timediff|uniquePlotIDs), REML = F, data = specrich)

# anova(Latonly.mll, Latonly2.mll)
```

